<a href="https://colab.research.google.com/github/iamnaymur/ml_meta_learning/blob/main/Multiple_Indicator_Cluster_Surveys_BDHS.ipynb" target="_parent"><img src="https://colab.research.google.com/assets/colab-badge.svg" alt="Open In Colab"/></a>

In [1]:
import pandas as pd
from google.colab import drive

drive.mount('/content/drive')

datapath = "/content/drive/MyDrive/Machine learning/BDHS_merged.parquet"

df = pd.read_parquet(datapath)

print("Dataset shape:", df.shape)

Drive already mounted at /content/drive; to attempt to forcibly remount, call drive.mount("/content/drive", force_remount=True).
Dataset shape: (167336, 1481)

In [2]:
print("Dataset shape:", df.shape)

# Column data types
print("\nData types:")
print(df.dtypes.value_counts())

display(df.iloc[:5, :10])

print("\nDuplicate column names:",
      df.columns.duplicated().sum())

Dataset shape: (167336, 1481)

Data types:
object     1470
int64        10
float64       1
Name: count, dtype: int64

   HH1  HH2 LN UF1 UF2 UF3 UFINT UF4  UF5  UF6
0    1    1  2
1    1    1  2
2    1    1  2
3    1    1  2
4    1    1  3   1   1   3   191   2  191  190

Duplicate column names: 0

In [3]:
missing = df.isna().sum()

missing_percent = (
    missing / len(df) * 100
).round(2)

missing_report = pd.DataFrame({
    "Missing_Count": missing,
    "Missing_Percent": missing_percent
})

missing_report = missing_report.sort_values(
    by="Missing_Percent",
    ascending=False
)

print("Columns with missing values:",
      (missing > 0).sum())

print("\nTop 20 columns with missing values:")
display(missing_report.head(20))

Columns with missing values: 0

Top 20 columns with missing values:

           Missing_Count  Missing_Percent
wqsweight              0              0.0
HH1                    0              0.0
HH2                    0              0.0
LN                     0              0.0
UF1                    0              0.0
UF2                    0              0.0
UF3                    0              0.0
UFINT                  0              0.0
UF4                    0              0.0
WQ29                   0              0.0
WQ27                   0              0.0
WQ26                   0              0.0
WQ25M                  0              0.0
WQ25H                  0              0.0
WQ24Y                  0              0.0
WQ24M                  0              0.0
WQ24D                  0              0.0
WQ21D                  0              0.0
WQ21C                  0              0.0
WQ21B                  0              0.0

In [4]:
duplicate_count = df.duplicated().sum()

print("Exact duplicate rows:", duplicate_count)

print("Duplicate percentage:",
      round(duplicate_count / len(df) * 100, 2))

Exact duplicate rows: 0
Duplicate percentage: 0.0

In [5]:

# Select object columns
object_cols = df.select_dtypes(include=['object']).columns

print("Total object columns:", len(object_cols))

# Display first 20 object columns with example values
for col in object_cols[:20]:
    print(f"\nColumn: {col}")
    print(df[col].dropna().unique()[:5])

Total object columns: 1470

Column: LN
['2' '3' '4' '5' '7']

Column: UF1
[' ' '1' '2' '3' '4']

Column: UF2
[' ' '1' '3' '6' '12']

Column: UF3
[' ' '3' '5' '4' '7']

Column: UFINT
[' ' '191' '193' '192' '194']

Column: UF4
[' ' '2' '4' '3' '6']

Column: UF5
[' ' '191' '193' '192' '194']

Column: UF6
[' ' '190' '180' '200' '210']

Column: UF7D
[' ' '22' '12' '13' '15']

Column: UF7M
[' ' '4' '3' '2' '5']

Column: UF7Y
[' ' '2025']

Column: UF8A
[' ' '1' '2']

Column: UF9
[' ' '1' '2']

Column: UF10
[' ' '1']

Column: UF17
[' ' '1']

Column: UF8H
[' ' '12' '11' '14' '15']

Column: UF8M
[' ' '6' '32' '42' '48']

Column: UF11H
[' ' '12' '11' '14' '15']

Column: UF11M
[' ' '17' '47' '55' '14']

Column: UF12
[' ' '2']